# permissions for end users to edit jdkcacerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jdkcacert-editor-role
rules:
- apiGroups:
  - delivery.caltamirano.com
  resources:
  - jdkcacerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.caltamirano.com
  resources:
  - jdkcacerts/status
  verbs:
  - get
