# permissions for end users to view jdkcacerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jdkcacert-viewer-role
rules:
- apiGroups:
  - delivery.caltamirano.com
  resources:
  - jdkcacerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.caltamirano.com
  resources:
  - jdkcacerts/status
  verbs:
  - get
