# permissions for end users to edit jdkkeystores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jdkkeystore-editor-role
rules:
- apiGroups:
  - jvm.caltamirano.com
  resources:
  - jdkkeystores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jvm.caltamirano.com
  resources:
  - jdkkeystores/status
  verbs:
  - get
