# permissions for end users to view jdkkeystores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jdkkeystore-viewer-role
rules:
- apiGroups:
  - jvm.caltamirano.com
  resources:
  - jdkkeystores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jvm.caltamirano.com
  resources:
  - jdkkeystores/status
  verbs:
  - get
